dist: bionic
language: python
python:
  - "3.6"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - pytest -sv test.py
  - python3 plugins/*_TEST.py
  - python3 gzdev.py repository list
  - python3 gzdev.py ign-docker-env citadel
  - python3 gzdev.py ign-docker-env dome --linux-distro ubuntu:bionic
