---
name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          cache: 'pip'
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@1a4bf406072a8d0efdf6faba94a34a096430472f # v2
